bin/trash: minor fixes

diff --git a/bin/trash b/bin/trash
--- a/bin/trash
+++ b/bin/trash
@@ -21,53 +21,87 @@
 
 VERSION="0.1"
 
-# Usage help
-usage () {
-  echo "usage info will go here"
-}
-
 # Directories
-DIR_LOCAL="$HOME/.local"
-DIR_LOCAL_SHARE="$HOME/.local/share"
-DIR_TRASH="$HOME/.local/share/Trash"
 DIR_TRASH_INFO="$HOME/.local/share/Trash/info"
 DIR_TRASH_FILES="$HOME/.local/share/Trash/files"
-# Test to make sure directories exist, if not create them
-if [ ! -d "$DIR_LOCAL" ]; then
-  mkdir $DIR_LOCAL
-  mkdir $DIR_LOCAL_SHARE
-  mkdir $DIR_TRASH
-  mkdir $DIR_TRASH_INFO
-  mkdir $DIR_TRASH_FILES
-else
-  if [ ! -d "$DIR_LOCAL_SHARE" ]; then
-    mkdir $DIR_LOCAL_SHARE
-    mkdir $DIR_TRASH
-    mkdir $DIR_TRASH_INFO
-    mkdir $DIR_TRASH_FILES
-  else
-    if [ ! -d "$DIR_TRASH" ]; then
-      mkdir $DIR_TRASH
-      mkdir $DIR_TRASH_INFO
-      mkdir $DIR_TRASH_FILES
-    else
-      if [ ! -d "$DIR_TRASH_INFO" ]; then
-        mkdir $DIR_TRASH_INFO
-      fi
-      if [ ! -d "$DIR_TRASH_FILES" ]; then
-        mkdir $DIR_TRASH_FILES
-      fi
-    fi
-  fi
-fi
 
-# Parse input
-if [ -z $@ ]; then
-  echo "ERROR: no input provided"
-  exit 1
-else
+# Usage help
+trash_usage () {
+
+cat <<EOF
+usage info will go here
+EOF
+
+}
+
+trash_dirs () {
+
+  # Test to see if directories exist, if not create them
+  [ -d "$DIR_TRASH_FILES" ] || { mkdir -p $DIR_TRASH_FILES ; return $? ; }
+  [ -d "$DIR_TRASH_FILES" ] || { mkdir -p $DIR_TRASH_FILES ; return $? ; }
+
+}
+
+tolower () {
+
+  echo "$@" | tr '[A-Z]' '[a-z]'
+
+}
+
+# Validate the answer to a yes or no question
+y_or_n_validate () {
+
+  local ANS
+
+  ANS="$(tolower $1)"
+
+  [ "$ANS" = "yes" ] && return 0
+  [ "$ANS" = "y" ] && return 0
+  [ "$ANS" = "no" ] && return 1
+  [ "$ANS" = "n" ] && return 1
+
+  return 2
+
+}
+
+# Ask a yes or no question
+y_or_n () {
+
+  local ANS
+  local RET
+
+  while true ; do
+    echo -n "$1 "
+    y_or_n_validate "$2"
+    RET="$?"
+    if [ "$RET" -eq "0" ] ; then
+      echo -n "(Y/n) "
+      read ANS
+      [ -z "$ANS" ] && return 0
+    elif [ "$RET" -eq "1" ] ; then
+      echo -n "(y/N)" 
+      read ANS
+      [ -z "$ANS" ] && return 1
+    else
+      echo -n "(y/n) "
+      read ANS
+    fi
+    y_or_n_validate "$ANS"
+    RET="$?"
+    [ "$RET" -lt "2" ] && return $RET
+  done
+
+}
+
+# Check for input
+[ -z $@ ] && { echo "ERROR: no input provided" ; exit 1 ; }
+
+# Make sure necessary directories exist before continuing
+trash_dirs || { echo "ERROR: trash directories could not be created" ; exit 1 ; }
+
   case $1 in
-    delete)
+
+    'delete')
       shift
       # TODO: allow deletion of specific files and directories
       ## Bypasses the trash-bin and permanently deletes the target
@@ -75,7 +109,8 @@ else
       # TODO: grep $@ for trash directories and if a match is found exit with error
       rm $@
       ;;
-    empty)
+
+    'empty')
       # Clear all files in trash
       # TODO: read files in $HOME/.local/share/Trash/info and
       # delete the .trashinfo file and the file it references
@@ -108,9 +143,7 @@ else
       echo "Are you sure you want to permanently delete $totalTrashfiles($totalTrashSize) (Y/N)"
       read confirmDeletion
 
-      while [ "$confirmDeletion" != "Y" ] || \
-            [ "$confirmDeletion" != "y" ] || \
-            [ "$confirmDeletion" != "N" ] || \
+      while [ "$confirmDeletion" != "y" ] || \
             [ "$confirmDeletion" != "n" ]; do
         case "$confirmDeletion" in
           Y|y)
@@ -137,7 +170,8 @@ else
         esac
       done
       ;;
-    list)
+
+    'list')
       # Lists the contents of the trash bin
       # TODO: add trash files and directories to a file (an index of trash contents)
       # WILL NOT WORK ONCE RANDOM NAMING IS IMPLEMENTED, NEEDS TO BE FIXED
@@ -150,7 +184,7 @@ while IFS= read -r f; do
   echo "$f"
 done
 for f in *.trashinfo; do
-
+ echo "test"
 done
 
 
@@ -163,17 +197,19 @@ for i in */; do
 done
 
 
-      for i in "$DIR_TRASH_INFO*.trashinfo"; do
-        cat .trashinfo | grep (path) | grep (filename)
+      for i in "$DIR_TRASH_INFO"; do
+        cat $1 | grep "path"
+        cat $1 | grep "filename"
 
-        print filename filesize orginal file path
+        # print filename filesize orginal file path
       done
       ;;
     -h|--help)
       usage
       ;;
-    *)
-      if [ -f $@ || -d $@ ]; then
+
+    *) # If no trash flags were found look for rm flags
+      if [ -f $@ ] || [ -d $@ ]; then
         # TODO: This will handle the 'rm' functionality and compatibility layer
         # TODO: implement ALL 'rm' options to ensure compatability, the options
         # will be mapped by the compatibility layer to trash options, this
@@ -214,9 +250,9 @@ done
       else
         echo "ERROR: invalid option: $1"
         echo
-        usage
+        trash_usage
         exit 1
       fi
       ;;
+
   esac
-fi
