syntax style changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -21,14 +21,6 @@ git remote set-url origin "$dotfilesRepo"
 git remote set-url --push origin "$dotfilesRepo"
 
 echo "Updating Config Files"
-config_latest
-if [ "$?" -gt "1" ] ; then
-  echo "Failed to update Config"
-  exit 1
-fi
+config_latest || { echo "Failed to update Configs" ; exit 1 ; }
 
-echo "Installing Config Files"
-if ! config_install ; then
-  echo "Failed to Install Config"
-  exit 1
-fi
+config_install || { echo "ERROR: configuration install failed" ; exit 1 ; }
