mod/ssh: e-mail not needed for keys

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,5 @@
 #!/usr/bin/env sh
 
-##[set email for ssh keys]
-export userEmail="codyopel@gmail.com"
-
 ##[list hostname of all workstations]
 export workStations='\(NOS-4-A2\|LGM\|Shivkatall\)'
 
@@ -17,7 +14,13 @@ git remote set-url --push origin https://github.com/codyopel/dotfiles
 
 echo "Updating Config Files"
 config_latest
-if [ "$?" -gt "1" ];then echo "Failed to update Config";exit 1;fi
+if [ "$?" -gt "1" ]; then
+  echo "Failed to update Config"
+  exit 1
+fi
 
 echo "Installing Config Files"
-if ! config_install;then echo "Failed to Install Config";exit 1;fi
+if ! config_install; then
+  echo "Failed to Install Config"
+  exit 1
+fi
