syntax style changes

diff --git a/lib/mod/comp b/lib/mod/comp
--- a/lib/mod/comp
+++ b/lib/mod/comp
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 
-##[sleeps the computer]
+# Sleeps the computer
 comp_sleep () {
 
   comp_lock || return 1
@@ -10,14 +10,14 @@ comp_sleep () {
 
 }
 
-##[powers off the computer]
+# Powers off the computer
 comp_off () {
 
   sudo_wrap poweroff
 
 }
 
-##[locks the screen]
+# Locks the screen
 comp_lock () {
 
   path_hasbin slock && {
@@ -27,8 +27,8 @@ comp_lock () {
 
   run_quiet gnome-screensaver-command -l && return 0
   run_quiet xscreensaver-command -lock && return 0
-  echo "Failed to lock the screen" >&2
 
+  echo "Failed to lock the screen" >&2
   return 1
 
 }
diff --git a/lib/mod/core b/lib/mod/core
--- a/lib/mod/core
+++ b/lib/mod/core
@@ -4,7 +4,7 @@
 symlink () {
 
   mkdir -p "$(dirname "$2")"
-  if [ "$(readlink -f "$2")" != "$1" ]; then
+  if [ "$(readlink -f "$2")" != "$1" ] ; then
     rm -rf "$2"
     ln -s "$1" "$2" 2>/dev/null || return 1
   fi
@@ -43,15 +43,15 @@ y_or_n () {
   local ANS
   local RET
 
-  while true; do
+  while true ; do
     echo -n "$1 "
     y_or_n_validate "$2"
     RET="$?"
-    if [ "$RET" -eq "0" ]; then
+    if [ "$RET" -eq "0" ] ; then
       echo -n "(Y/n) "
       read ANS
       [ -z "$ANS" ] && return 0
-    elif [ "$RET" -eq "1" ]; then
+    elif [ "$RET" -eq "1" ] ; then
       echo -n "(y/N)" 
       read ANS
       [ -z "$ANS" ] && return 1
@@ -72,7 +72,7 @@ dir_tmp () {
   local DIR_TMP
 
   dir_tmp_tryall
-  [ "$DIR_TMP" = "" ] && { echo "Failed to find a temporary folder" >&2; return 1; }
+  [ "$DIR_TMP" = "" ] && { echo "Failed to find a temporary folder" >&2 ; return 1 ; }
   [ ! -d "$DIR_TMP" ] && mkdir "$DIR_TMP" && chmod 0700 "$DIR_TMP"
   symlink "$DIR_TMP" "$HOME/.tmp"
   mkdir "$DIR_TMP/cache" >/dev/null 2>&1
@@ -93,6 +93,7 @@ dir_tmp_tryall() {
 dir_tmp_one () {
 
 	[ -w "$1" ] || return 1
+
   mount | grep '\(tmpfs\|ramfs\)' | grep $1 >/dev/null || return 1
   DIR_TMP="$1/$USER"
 
@@ -102,6 +103,7 @@ dir_tmp_one () {
 path_bin () {
 
   [ "$#" -ne "1" ] && return 2
+
   path_hasbin $1 && type $1 | awk '{print $3}' && return 0
 
   return 1
@@ -112,6 +114,7 @@ path_bin () {
 proc_exists () {
 
   [ "$#" -ne "1" ] && return 1
+
   kill -0 $1 >/dev/null 2>&1
 
 }
@@ -135,7 +138,7 @@ path_add () {
 # Wraps the command in sudo if sudo exists and runs it
 sudo_wrap () {
 
-  if path_hasbin sudo; then
+  if path_hasbin sudo ; then
     sudo $@
   else
     $@
diff --git a/lib/mod/extract b/lib/mod/extract
--- a/lib/mod/extract
+++ b/lib/mod/extract
@@ -2,73 +2,74 @@
 
 extract () {
 
-  if [ -z $1 ]; then
-    echo "ERROR: no input provided"; exit 1
-  elif [ -f $1 ]; then
+  if [ -z $1 ] ; then
+    echo "ERROR: no input provided"
+    return 1
+  elif [ -f $1 ] ; then
     case $1 in
 
       *.tar)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xf $1
         ;;
 
       *.tar.bz2)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xjf $1
         ;;
 
       *.tbz2)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xjf $1
         ;;
 
       *.bz2)
-        path_hasbin bunzip2 || { echo "'bunzip2' not installed" ; exit 1; }
+        path_hasbin bunzip2 || { echo "'bunzip2' not installed" ; return 1 ; }
         bunzip2 $1
         ;;
 
       *.tar.gz)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xzf $1
         ;;
 
       *.tgz)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xzf $1
         ;;
 
       *.gz)
-        path_hasbin gunzip || { echo "'gunzip' not installed" ; exit 1; }
+        path_hasbin gunzip || { echo "'gunzip' not installed" ; return 1 ; }
         gunzip $1
         ;;
 
       *.tar.xz)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xJf $1
         ;;
 
       *.txz)
-        path_hasbin tar || { echo "'tar' not installed" ; exit 1; }
+        path_hasbin tar || { echo "'tar' not installed" ; return 1 ; }
         tar xJf $1
         ;;
 
       *.rar)
-        path_hasbin unrar || { echo "'unrar' not installed" ; exit 1; }
+        path_hasbin unrar || { echo "'unrar' not installed" ; return 1 ; }
         unrar e $1
         ;;
 
       *.zip)
-        path_hasbin unzip || { echo "'unzip' not installed" ; exit 1; }
+        path_hasbin unzip || { echo "'unzip' not installed" ; return 1 ; }
         unzip $1
         ;;
 
       *.Z)
-        path_hasbin uncompress || { echo "'uncompress' not installed" ; exit 1; }
+        path_hasbin uncompress || { echo "'uncompress' not installed" ; return 1 ; }
         uncompress $1
         ;;
 
       *.7z)
-        path_hasbin 7z || { echo "'7zip' not installed" ; exit 1; }
+        path_hasbin 7z || { echo "'7zip' not installed" ; return 1 ; }
         7z x $1
         ;;
 
@@ -80,4 +81,5 @@ extract () {
   else
       echo "'$1' is not a file"
   fi
+
 }
