mod/core: added directory and file existence check functions

diff --git a/lib/mod/core b/lib/mod/core
--- a/lib/mod/core
+++ b/lib/mod/core
@@ -158,3 +158,39 @@ toupper () {
   echo "$@" | tr '[a-z]' '[A-Z]'
 
 }
+
+dir_check () {
+
+  [ -d "$1" ] || { mkdir -p "$1" ; return $? ; }
+
+  return 0
+
+}
+
+dir_exist () {
+
+  dir_check "$1" || { echo "ERROR: failed to create directory: $1" ; }
+
+  echo "Created directory: $1"
+
+  return 0
+
+}
+
+file_check () {
+
+  [ -f "$1" ] || { touch "$1" ; return $? ; }
+
+  return 0
+
+}
+
+file_exist () {
+
+  file_check "$1" || { echo "ERROR: failed to create file: $1" ; }
+
+  echo "Created file: $1"
+
+  return 0
+
+}
