fixed syntax error: missing fi

diff --git a/lib/mod/pkgmgmt b/lib/mod/pkgmgmt
--- a/lib/mod/pkgmgmt
+++ b/lib/mod/pkgmgmt
@@ -105,7 +105,7 @@ pkg_install () {
     echo "OSX not yet supported"
     ## homebrew
   else
-  echo "Failed to find an install procedure, unsupported os" >&2
+  echo "Failed to find an install procedure, unsupported os" >&2;fi
   return 1
 }
 
