mod/vol: refactored volume module

diff --git a/lib/mod/vol b/lib/mod/vol
--- a/lib/mod/vol
+++ b/lib/mod/vol
@@ -1,27 +1,24 @@
 #!/usr/bin/env sh
 
-# Configuration
-volumeMixer="1"
-defaultIncrement="5"
-
 vol_path () {
 
   # Make sure 'pactl' is installed
-  path_hasbin pactl || { echo "'pactl' not installed" ; return 1 ; }
+  path_hasbin pactl || { echo "$(termclr red 0)ERROR: 'pactl' is not installed$(termclr reset 0)" ; return 1 ; }
   return 0
 
 }
 
 vol_usage () {
 
-  echo "usage: vol [option] [argument]"
+  echo
+  echo "Usage: vol [integer/option]"
   echo
   echo "Options:"
-  echo "     up   - increase volume by \`argument'"
-  echo "     down - decrease volume by \`argument'"
-  echo "     set  - set volume percentage"
-  echo "     mute - toggle mute on and off"
-  echo "     h, -h, --help - display this message"
+  echo "     [0-150] - set volume percentage"
+  echo "     up      - increase volume by \`argument'"
+  echo "     down    - decrease volume by \`argument'"
+  echo "     mute    - toggle mute on and off"
+  echo "     --help  - display this message"
 
 }
 
@@ -30,55 +27,45 @@ vol () {
   # If 'pactl' is not installed, be done now
   vol_path || return 1
 
+  volumeActiveSoundCard=$(\
+    pactl list sinks | \
+    grep --before-context=1 "State: RUNNING" | \
+    awk -F'[^0-9]*' '/Sink\ \#/ { print $2 ; exit }')
+
   # Parse Arguments
   case "$1" in
     '')
-      volumeCurrent="doesn't work yet"
+      volumeCurrent=$(pactl list sinks | \
+        grep --after-context=9 "Sink #${volumeActiveSoundCard}" | \
+        grep "Volume:" | \
+        awk '/[^0-9]*\%/ { print $5 ; exit }')
       echo "Volume: ${volumeCurrent}"
       ;;
-    'up')
-      volumeCommand="set-sink-volume"
-      if [ -z "$2" ]; then
-        volumeModify="+${defaultIncrement}%"
-      else
-        volumeModify="+${2}%"
-      fi
+    U|u|[U,u][P,p])
+      pactl set-sink-volume ${volumeActiveSoundCard} -- "+5%"
       ;;
-    'down')
-      volumeCommand="set-sink-volume"
-      if [ -z "$2" ]; then
-        volumeModify="-${defaultIncrement}%"
-      else
-        volumeModify="-${2}%"
-      fi
+    D|d|[D,d][O,o][W,w][N,n])
+      pactl set-sink-volume ${volumeActiveSoundCard} -- "-5%"
       ;;
-    'set')
-      volumeCommand="set-sink-volume"
-      if [ -z "$2" ]; then
-        echo "ERROR: 'vol set' requires an argument"
-        return 1
-      else
-        volumeModify="${2}%"
-      fi
+    M|m|[M,m][U,u][T,t][E,e])
+      pactl set-sink-mute ${volumeActiveSoundCard} toggle
       ;;
-    'mute')
-      volumeCommand="set-sink-mute"
-      volumeModify="toggle"
-      ;;
-    '-h'|'--help')
+    '--help')
       vol_usage
       return 0
       ;;
     *)
-      echo "Unrecognized option \`$1'"
-      echo
-      vol_usage
-      return 1
+      case $1 in
+        [0-9]|[1-9][0-9]|1[0-4][0-9]|150)
+          pactl set-sink-volume ${volumeActiveSoundCard} -- "${1}%"
+          ;;
+        *)
+          echo -e "$(termclr red 0)ERROR: must be an integer between 0 and 150$(termclr reset 0)"
+          vol_usage
+          return 1
+          ;;
+      esac
       ;;
   esac
-
-  # Actual volume change
-  pactl ${volumeCommand} ${volumeMixer} ${volumeModify}
-
 
 }
