lib/integrity: use more descriptive error message

diff --git a/lib/integrity b/lib/integrity
--- a/lib/integrity
+++ b/lib/integrity
@@ -5,7 +5,7 @@ require_app () {
 
   which "$1" >/dev/null 2>&1
   if [ "$?" -ne "0" ] ; then
-    echo "Requires: $1" >&2
+    echo "ERROR: required dependency '$1' is not installed" >&2
     exit 2
   fi
 
