lib/loader: don't use symlinks

diff --git a/lib/loader b/lib/loader
--- a/lib/loader
+++ b/lib/loader
@@ -80,14 +80,16 @@ dir_try () { # Determines the top level configuration directory
 
 dir_conf () {
 
-  [ -z "$DIR_CONF" ] || { echo "$DIR_CONF" ; return 0 ; }
-  dir_try "$1" && return 0
-  dir_try "$HOME/.zshrc" && return 0
-  dir_try "$HOME/.bashrc" && return 0
-  dir_try "$HOME/.xinitrc" && return 0
+  #[ -z "$DIR_CONF" ] || { echo "$DIR_CONF" ; return 0 ; }
+  #dir_try "$1" && return 0
+  #dir_try "$HOME/.zshrc" && return 0
+  #dir_try "$HOME/.bashrc" && return 0
+  #dir_try "$HOME/.xinitrc" && return 0
 
-  echo "Failed to find the configuration directory" >&2
-  return 1
+  #echo "Failed to find the configuration directory" >&2
+  #return 1
+
+  echo "$DOTFILES_DIR"
 
 }
 
@@ -121,7 +123,7 @@ array_forall () {
 
 reload_all () { # Allows the functions to be reloaded at any time
 
-  . "$(dir_conf)/lib/loader"
+  . "$DOTFILES_DIR/lib/loader"
 
 }
 
