fix dotfiles directory

diff --git a/lib/loader b/lib/loader
--- a/lib/loader
+++ b/lib/loader
@@ -1,5 +1,12 @@
 #!/usr/bin/env sh
 
+# Find and set dotfiles directory
+DOTFILES_DIR=$(cat "$HOME/.dotfiles.dir")
+
+[ -z "$DOTFILES_DIR" ] && { echo "Failed to find the configuration directory" ; exit 1 ; }
+
+export DOTFILES_DIR
+
 [ -z "$RUNNER" ] && RUNNER=0
 
 path_abs () { # Resolves the name of the binary
@@ -89,20 +96,14 @@ dir_conf () {
   #echo "Failed to find the configuration directory" >&2
   #return 1
 
-  local DOTFILES_DIR
-
-  DOTFILES_DIR=$(cat "$HOME/.dotfiles.dir")
-
-  [ -z "$DOTFILES_DIR" ] && { echo "Failed to find the configuration directory" ; return 1 ; }
+  echo "$DOTFILES_DIR"
 
   return 0
 
 }
 
 # Loads the shell specific fixes
-svar DIRCONF dir_conf "$0" || return 1
-
-. "$DIRCONF/lib/fixes.$(shell_nov)" 2>/dev/null || {
+. "$DOTFILES_DIR/lib/fixes.$(shell_nov)" 2>/dev/null || {
   echo "Failed to load the fixes for the current shell" >&2
   exit 1
 }
@@ -149,7 +150,7 @@ load_all () {
 
   svar DIRCONF dir_conf || return 1
 
-  array_from_str MODS "$(find "$DIRCONF/$1" -type f)"
+  array_from_str MODS "$(find "$DOTFILES_DIR/$1" -type f)"
   array_forall MODS load_one
 
 }
diff --git a/lib/mod/config b/lib/mod/config
--- a/lib/mod/config
+++ b/lib/mod/config
@@ -3,8 +3,7 @@
 git_cd () {
 
   if [ -z "$1" ] ; then
-    svar DIRCONF dir_conf || return 1
-    cd "$DIRCONF"
+    cd "$DOTFILES_DIR"
   else
     cd "$1"
   fi
@@ -83,9 +82,7 @@ git_sub_pull () { # Update the submodules
 
   git_cd $1 || return 2
 
-  svar DIRCONF dir_conf || return 2
-
-  STR="$(git submodule -q foreach --recursive "\"$DIRCONF/bin/run\" git_pull_nostat .")" || return 2
+  STR="$(git submodule -q foreach --recursive "\"$DOTFILES_DIR/bin/run\" git_pull_nostat .")" || return 2
 
   [ "$(echo "$STR" | grep 'Updated')" = "" ]
 
@@ -150,7 +147,7 @@ config_ln () { # Links the configuration file to its proper dotfile
   [ "$#" -eq "0" ] && return 1
 
   for LN in $@ ; do
-    symlink "$(dir_conf)/dotfiles/$LN" "$HOME/.$LN" || { echo "ERROR: failed to symlink $LN" 2> /dev/null ; }
+    symlink "$DOTFILES_DIR/dotfiles/$LN" "$HOME/.$LN" || { echo "ERROR: failed to symlink $LN" 2> /dev/null ; }
     [ "$?" -eq "0" ] && echo "  Symlinked $LN"
   done
 
@@ -160,12 +157,12 @@ config_install () { # Installs the configuration files
 
   echo "Configuring directories"
   # Bootstrap by sourcing file to find directory to install config
-  . "$(dir_conf)/dotfiles/config/user-dirs.dirs"
+  . "$DOTFILES_DIR/dotfiles/config/user-dirs.dirs"
   config_ln "config/user-dirs.dirs"
   xdg_dirs
 
   echo "Configuring PATH"
-  symlink "$(dir_conf)/bin" "$HOME/.bin"
+  symlink "$DOTFILES_DIR/bin" "$HOME/.bin"
   path_add "$HOME/.bin"
 
   echo "Configuring Desktop Environment"
