minor syntax changes

diff --git a/lib/loader b/lib/loader
--- a/lib/loader
+++ b/lib/loader
@@ -22,19 +22,16 @@ svar () {
   return "$RET"
 }
 
-# Returns the shell executing the current script
+##[returns the shell executing the current script]
 shell () {
   local LSHELL; local LPROC;
   LPROC="$(ps hp $$ | grep "$$")"
-
-  # Workaround for su spawned shells
-  if [ -n "$(echo "$LPROC" | grep '\-su')" ]; then
+  ##[workaround for su spawned shells]
+  if [ -n "$(echo "$LPROC" | grep '\-su')" ];then
     LSHELL="$(basename "$(echo "$LPROC" | sed 's/^.*(\([^)]*\)).*$/\1/')")"
   else
-    LSHELL="$(basename "$(echo "$LPROC" | sed 's/-//' | awk '{print $5}')")"
-  fi
-
-  # Resolve Symlinked Shells
+    LSHELL="$(basename "$(echo "$LPROC" | sed 's/-//' | awk '{print $5}')")";fi
+  ##[resolve symlinked shells]
   basename "$(readlink -f "$(path_abs "$LSHELL")")"
 }
 
@@ -55,7 +52,7 @@ dir_try () {
   cd "$OLD"
 }
 dir_conf () {
-  [ -z "$DIR_CONF" ] || { echo "$DIR_CONF"; return 0; }
+  [ -z "$DIR_CONF" ] || { echo "$DIR_CONF";return 0; }
   dir_try "$1" && return 0
   dir_try "$HOME/.zshrc" && return 0
   dir_try "$HOME/.bashrc" && return 0
@@ -80,7 +77,7 @@ array_empty () {
 }
 array_forall () {
   [ "$(array_size $1)" -gt "0" ] || return 0
-  for I in $(seq 0 $(expr $(array_size $1) - 1)); do
+  for I in $(seq 0 $(expr $(array_size $1) - 1));do
     eval "$2 \"$(array_at $1 $I)\"" || return 1
   done
 }
@@ -93,7 +90,7 @@ reload_all () {
 # Source Modules
 load_one () {
   [ "$(echo "$1" | grep '\(~$\|^#\)')" != "" ] && return 0
-  . "$1" || { echo "Failed to load module $1"; return 1; }
+  . "$1" || { echo "Failed to load module $1";return 1; }
 }
 load_all () {
   [ "$#" -ge "1" ] || return 1
